security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    password_hashers:
        AMREU\UserBundle\Model\UserInterface: bcrypt
        legacy:
            algorithm: sodium

        App\Entity\User:
            algorithm: bcrypt
            migrate_from: 
                - legacy
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        # fos_userbundle:
        #     id: fos_user.user_provider.username

        amreu_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: amreu_user_provider
            custom_authenticators:
                    - amreu.login.form.passportauthenticator

            entry_point: amreu.login.form.passportauthenticator

            logout:
                path: user_security_logout

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            switch_user: { role: ROLE_SUPER_ADMIN }

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/(es|eu)?/login$, role: PUBLIC_ACCESS }
#        - { path: ^/[0-9][0-9][0-9][0-9]?[0-9]?/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/doc/, role: [ROLE_USER] }
        - { path: ^/(eu|es)/, role: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/admin/user, role: [ROLE_ADMIN] }
        - { path: ^/admin/, role: [ROLE_ADMIN, ROLE_USER] }