twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        zzoo_aplikazioaren_API_url: '%zzoo_aplikazioaren_API_url%'
    form_themes:
        - bootstrap_3_layout.html.twig
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'