version:  '3.7'
services:
    mariadb:
        image: mariadb:10.5.3
        container_name: zergaordenantzak-mariadb
        volumes:
            - mariadb_zzoo:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=pasaia
            - MYSQL_DATABASE=zzoo
            - MYSQL_USER=pasaia
            - MYSQL_PASSWORD=pasaia
        ports:
            - "3306:3306"
        networks:
            - zzoo

    php:
        container_name: zergaordenantzak-php
        env_file: ./.env
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        restart: always
        depends_on:
            - mariadb
        volumes:
            - '.:/usr/src/app'
        user: 1000:1000
        environment:
            - APP_ENV=dev
            - PHP_IDE_CONFIG=serverName=zergaordenantzak.test
            - XDEBUG_CONFIG=remote_host=192.168.2.8
        networks:
            - zzoo

    nginx:
        container_name: zergaordenantzak-nginx
        image: nginx:1.15.3-alpine
        restart: always
        volumes:
            - '.:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        depends_on:
            - php
        ports:
            - 80:80
        networks:
            - zzoo

volumes:
    mariadb_zzoo:

networks:
  zzoo:
      driver: bridge
