version:  '3.7'
services:
    mariadb:
        image: mariadb:10.5.3
        env_file: ./.env.local
        container_name: zergaordenantzak-db
        volumes:
            - db_zzoo:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - zzoo

    app:
        container_name: zergaordenantzak-php
        env_file: ./.env.local
        build:
            context: .
            dockerfile: docker/php/Dockerfile
            args:
                - DOCKER_TIMEZONE=${DOCKER_TIMEZONE}
                - USER_ID=${USER_ID}
                - GROUP_ID=${GROUP_ID}
        restart: always
        depends_on:
            - mariadb
        volumes:
            - '.:/usr/src/app'
        environment:
            - APP_ENV=dev
            - PHP_IDE_CONFIG=serverName=zergaordenantzak.test
            - XDEBUG_CONFIG=remote_host='host.docker.internal'
        networks:
            - zzoo

    nginx:
        container_name: zergaordenantzak-nginx
        env_file: ./.env.local
        image: nginx:1.15.3-alpine
        restart: always
        volumes:
            - '.:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
            - './docker/nginx/ssl/:/etc/nginx/ssl/'
        depends_on:
            - app
        ports:
            - 80:80
            - 443:443
        networks:
            - zzoo

volumes:
    db_zzoo:

#networks:
#  zzoo:
#      driver: bridge
networks:
  zzoo:
    external: true
