<?php

namespace AppBundle\Repository;

/**
 * AzpiatalaparrafoaondorenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AzpiatalaparrafoaondorenRepository extends \Doctrine\ORM\EntityRepository
{
}
