<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * OrdenantzaRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class OrdenantzaRepository extends EntityRepository
{
    public function getOrdenantzabat($id)
    {
        $em = $this->getEntityManager();


        $dql = "
            SELECT o,p,a,ap,az,azp,k,m,b
                FROM AppBundle:Ordenantza o
                    LEFT JOIN o.parrafoak p
                    LEFT JOIN o.atalak a
                    LEFT JOIN a.parrafoak ap
                    LEFT JOIN a.azpiatalak az
                    LEFT JOIN az.parrafoak azp
                    LEFT JOIN az.kontzeptuak k
                    LEFT JOIN k.kontzeptumota m
                    LEFT JOIN k.baldintza b
                WHERE o.id = :id
        ";

//        $qb = $this->createQueryBuilder('o')
//            ->select('o,p,a')
//            ->innerJoin('o.parrafoak','p')
//            ->innerJoin('o.atalak','a')
//            ->leftJoin('a.parrafoak','ap')
//            ->where('o =:id')->setParameter('id', $id)
//            ->where('a =:id')->setParameter('id', $id)
//            ->getQuery()
//            ->getResult(Query::HYDRATE_ARRAY);

        $consulta = $em->createQuery($dql);
        $consulta->setParameter('id', $id);
//        print_r($consulta->getSQL());
        return $consulta->getResult(Query::HYDRATE_ARRAY);

//        return $qb;
    }
}
