<?php

namespace AppBundle\Repository;

/**
 * UdalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UdalaRepository extends \Doctrine\ORM\EntityRepository
{
}
